begin;

DELETE from KR_TBL_DATASRC_FIELD_DEF;

insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 0, 'krdb_timestamp', '入库时间戳 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 1, 'created_at', '微博创建时间 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 2, 'user_id', '用户ID ', 'D', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 3, 'user_screen_name', '用户昵称 ', 'S', 50, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 4, 'user_name', '用户友好显示名称 ', 'S', 50, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 5, 'user_gender', '用户性别 ', 'S', 2, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 6, 'user_verified', '用户是否是微博认证用户 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 7, 'user_followers_count', '用户粉丝数 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 8, 'user_friends_count', '用户关注数 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 9, 'user_statuses_count', '用户微博数 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 10, 'user_favourites_count', '用户收藏数 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 11, 'user_online_status', '用户的在线状态 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 12, 'user_avatar_large', '用户大头像地址 ', 'S', 100, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 13, 'id', '微博ID ', 'D', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '12');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 14, 'mid', '微博MID ', 'D', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '14');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 15, 'text', '微博信息内容 ', 'S',  500, '1', '0', '3,4,7,8', ' ', 38, '  ', '  ');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 16, 'source', '微博来源 ', 'S', 100, '1', '0', '3,4,7,8', ' ', 19, '  ', '04');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 17, 'favorited', '是否已收藏', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '  ');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 18, 'truncated', '是否被截断 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '  ');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 19, 'thumbnail_pic', '缩略图片地址 ', 'S', 100, '1', '0', '3,4,7,8', ' ', 0, '  ', '  ');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 20, 'bmiddle_pic', '中等尺寸图片地址 ', 'S', 100, '1', '0', '3,4,7,8', ' ', 0, '  ', '  ');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 21, 'original_pic', '原始图片地址 ', 'S', 100, '1', '0', '3,4,7,8', ' ', 0, '  ', '  ');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 22, 'retweeted_status_id', '被转发的原微博信息id ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 23, 'reposts_count', '转发数 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 24, 'comments_count', '评论数 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 25, 'attitudes_count', '表态数 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 26, 'visible_type', '微博的可见性 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
insert into KR_TBL_DATASRC_FIELD_DEF (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, IS_USED_BY_FLT, IS_USED_BY_RULE, FIELD_WEB_TYPE, FIELD_TEXT_RECT, FIELD_DATADIC_RECT, FIELD_USE_RECT, FIELD_SET_RECT)
values (2, 27, 'visible_list_id', '微博的指定可见分组 ', 'L', 8, '1', '0', '3,4,7,8', ' ', 0, '  ', '16');
commit;
