/******************************************************************************
 *             This file was generated by rapodbc automatically.              *
 *                     Don't modify it by yourself!                           *
 *   Author: Tiger(https://github.com/AbsoluteTiger/rapodbc)                  *
 *      Time: Mon Oct 11 17:58:42 2021                               *
 ******************************************************************************/

#ifndef __ParamObjectIns_H__
#define __ParamObjectIns_H__
#include "dbs/dbs_basopr.h"

typedef struct 
{
    SQLHSTMT    hstmt;
    char        caInParamVersion[20+1];
    char        caInParamClassName[30+1];
    char        caInParamObjectKey[30+1];
    char        caInParamObjectString[1024+1];
}T_ParamObjectIns;

extern int dbsParamObjectIns(T_DbsEnv *dbsenv, T_ParamObjectIns *ptParamObjectIns);

#endif

