/******************************************************************************
 *             This file was generated by rapodbc automatically.              *
 *                     Don't modify it by yourself!                           *
 *   Author: Tiger(https://github.com/AbsoluteTiger/rapodbc)                  *
 *      Time: Mon Oct 11 17:58:42 2021                               *
 ******************************************************************************/

#include <stdio.h> 
#include <stdlib.h> 
#include <string.h> 

#include "param_object_ins.h"

int dbsParamObjectIns(T_DbsEnv *dbsenv, T_ParamObjectIns *ptParamObjectIns)
{
    SQLRETURN  rc = SQL_SUCCESS;
    SQLLEN iLen = 0, iNTS = SQL_NTS;
          char hcaParamObjectInsSql[2048+1]={0};
          strcpy(hcaParamObjectInsSql, "INSERT INTO  KR_PARAM_OBJECT   (  PARAM_VERSION,  PARAM_CLASS_NAME,  PARAM_OBJECT_KEY,  PARAM_OBJECT_STRING  )  VALUES  (   ? ,   ? ,   ? ,   ?   )  ");
    rc = SQLAllocHandle(SQL_HANDLE_STMT, dbsenv->hdbc, &ptParamObjectIns->hstmt);
    if (rc != SQL_SUCCESS) {
        dbsGetError(dbsenv, ptParamObjectIns->hstmt);
        SQLFreeHandle(SQL_HANDLE_STMT, ptParamObjectIns->hstmt);
        return rc;
    }
    rc = SQLPrepare(ptParamObjectIns->hstmt, (SQLCHAR *)hcaParamObjectInsSql, SQL_NTS);
    if (rc != SQL_SUCCESS) {
        dbsGetError(dbsenv, ptParamObjectIns->hstmt);
        SQLFreeHandle(SQL_HANDLE_STMT, ptParamObjectIns->hstmt);
        return rc;
    }
    rc = SQLBindParameter(ptParamObjectIns->hstmt, 1, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_C_CHAR, 20, 0, ptParamObjectIns->caInParamVersion, 20, &iNTS);
    if (rc != SQL_SUCCESS) {
        dbsGetError(dbsenv, ptParamObjectIns->hstmt);
        SQLFreeHandle(SQL_HANDLE_STMT, ptParamObjectIns->hstmt);
        return rc;
    }
    rc = SQLBindParameter(ptParamObjectIns->hstmt, 2, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_C_CHAR, 30, 0, ptParamObjectIns->caInParamClassName, 30, &iNTS);
    if (rc != SQL_SUCCESS) {
        dbsGetError(dbsenv, ptParamObjectIns->hstmt);
        SQLFreeHandle(SQL_HANDLE_STMT, ptParamObjectIns->hstmt);
        return rc;
    }
    rc = SQLBindParameter(ptParamObjectIns->hstmt, 3, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_C_CHAR, 30, 0, ptParamObjectIns->caInParamObjectKey, 30, &iNTS);
    if (rc != SQL_SUCCESS) {
        dbsGetError(dbsenv, ptParamObjectIns->hstmt);
        SQLFreeHandle(SQL_HANDLE_STMT, ptParamObjectIns->hstmt);
        return rc;
    }
    rc = SQLBindParameter(ptParamObjectIns->hstmt, 4, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_C_CHAR, 1024, 0, ptParamObjectIns->caInParamObjectString, 1024, &iNTS);
    if (rc != SQL_SUCCESS) {
        dbsGetError(dbsenv, ptParamObjectIns->hstmt);
        SQLFreeHandle(SQL_HANDLE_STMT, ptParamObjectIns->hstmt);
        return rc;
    }
    rc = SQLExecute(ptParamObjectIns->hstmt);
    if (rc != SQL_SUCCESS) {
        dbsGetError(dbsenv, ptParamObjectIns->hstmt);
        SQLFreeHandle(SQL_HANDLE_STMT, ptParamObjectIns->hstmt);
        return rc;
    }
    SQLFreeHandle(SQL_HANDLE_STMT, ptParamObjectIns->hstmt);
    return rc;
}


