CREATE TABLE KR_PARAM_OBJECT
    (
        PARAM_ID INTEGER NOT NULL,
        PARAM_VERSION VARCHAR(20) NOT NULL,
        PARAM_CLASS_NAME VARCHAR(30) NOT NULL,
        PARAM_OBJECT_KEY VARCHAR(30) NOT NULL,
        PARAM_OBJECT_STRING VARCHAR(2048) NOT NULL,
        PRIMARY KEY (PARAM_ID)
    );