begin;

DELETE from KR_TBL_SDI_DEF;

insert into KR_TBL_SDI_DEF (SDI_ID, SDI_NAME, SDI_DESC, SDI_TYPE, SDI_VALUE_TYPE, SDI_AGGR_FUNC, SDI_FREE_FUNC, STATISTICS_DATASRC, STATISTICS_INDEX, STATISTICS_FIELD, STATISTICS_LOCATION, LOCATION_PROPERTY, SDI_FILTER_STRING, SDI_STATUS, REC_CRET_DTTM, LST_UPD_DTTM, LST_UPD_USER_ID)
values (1, 'last_trans_time', '上笔交易金额大于50并且交易地点满足正则的交易时间', '0', 'S', ' ',' ', 1, 1, 4, 1, 'R', '(F_7>50)&&(F_8##[^TRANS_LOCATION*]);', '0', '20120523141050   ', '20120523141050   ', 'Tiger');

commit;
