begin;

DELETE from KR_TBL_DATASRC_FIELD;

insert into KR_TBL_DATASRC_FIELD (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, FIELD_DATADIC) values (1, 0, 'krdb_timestamp', '入库时间戳 ', 'L', 8, 0);
insert into KR_TBL_DATASRC_FIELD (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, FIELD_DATADIC) values (1, 1, 'trans_timestamp', '交易时间戳 ', 'L', 8, 0);
insert into KR_TBL_DATASRC_FIELD (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, FIELD_DATADIC) values (1, 2, 'cust_no', '客户号 ', 'S', 20, 0);
insert into KR_TBL_DATASRC_FIELD (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, FIELD_DATADIC) values (1, 3, 'trans_date', '交易日期 ', 'S', 8, 0);
insert into KR_TBL_DATASRC_FIELD (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, FIELD_DATADIC) values (1, 4, 'trans_time', '交易时间 ', 'S', 6, 0);
insert into KR_TBL_DATASRC_FIELD (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, FIELD_DATADIC) values (1, 5, 'flow_no', '交易流水号 ', 'S',  15, 0);
insert into KR_TBL_DATASRC_FIELD (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, FIELD_DATADIC) values (1, 6, 'trans_type', '交易类型 ', 'S', 2, 0);
insert into KR_TBL_DATASRC_FIELD (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, FIELD_DATADIC) values (1, 7, 'trans_amt', '交易金额(人民币) ', 'D', 8, 0);
insert into KR_TBL_DATASRC_FIELD (DATASRC_ID, FIELD_ID, FIELD_NAME, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, FIELD_DATADIC) values (1, 8, 'trans_loc', '交易地点 ', 'S', 100, 0);

commit;
